name: ci
on:
  pull_request:

defaults:
  run:
    shell: bash

env:
  TERM: xterm

jobs:
  build-linux:
    uses: ./.github/workflows/.build-linux.yml

  windows-install-deps:
    runs-on: windows-2022
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: ci/setup-node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: "package.json"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: ci/cache-node-modules
        id: cache-node-modules
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
        with:
          path: node_modules
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-node-modules
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: ci/install-dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          npm ci --openssl_fips=''

  build-win-no-installer:
    runs-on: windows-2022
    needs:
      - windows-install-deps
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: ci/setup-node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: "package.json"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: ci/cache-node-modules
        id: cache-node-modules
        uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
        with:
          path: node_modules
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-node-modules
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: ci/install-node-gyp
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          choco install yq --version 4.15.1 -y
          npm i -g node-gyp
          node-gyp install
          node-gyp install --devdir="C:\Users\runneradmin\.electron-gyp" --target=$(jq -r .devDependencies.electron package.json) --dist-url="https://electronjs.org/headers"
      - name: ci/install-dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          npm ci --openssl_fips=''
      - name: ci/test
        uses: ./.github/actions/test
      - name: ci/build
        run: |
          mkdir -p ./build
          npm run package:windows
          bash -x ./scripts/patch_updater_yml.sh
          mkdir -p ./build/win
          bash -x ./scripts/cp_artifacts.sh release ./win/
      - name: ci/upload-build
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: build
          path: ./build
          retention-days: 14 ## No need to keep CI builds more than 14 days
      - name: ci/test-report
        uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226 # v1.6.0
        if: success() || failure()
        with:
          name: Windows Tests
          path: test-result.xml
          reporter: jest-junit

  build-mac-no-dmg:
    runs-on: macos-12
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: ci/setup-node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: "package.json"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: ci/install-dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          brew install yq
          jq '.mac.target=["zip"]' electron-builder.json | jq '.mac.gatekeeperAssess=false' > /tmp/electron-builder.json && cp /tmp/electron-builder.json .
          npm ci
      - name: ci/test
        uses: ./.github/actions/test
      - name: ci/build
        run: |
          mkdir -p ./build
          npm run package:mac
          bash -x ./scripts/patch_updater_yml.sh
          mkdir -p ./build/macos
          bash -x ./scripts/cp_artifacts.sh release ./macos/
      - name: ci/upload-build
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: build
          path: ./build
          retention-days: 14 ## No need to keep CI builds more than 14 days
      - name: ci/test-report
        uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226 # v1.6.0
        if: success() || failure()
        with:
          name: MacOS Tests
          path: test-result.xml
          reporter: jest-junit
