name: Electron Playwright Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.MM_DESKTOP_E2E_AWS_ACCESS_KEY_ID }}
  AWS_S3_BUCKET: "mattermost-cypress-report"
  AWS_SECRET_ACCESS_KEY: ${{ secrets.MM_DESKTOP_E2E_AWS_SECRET_ACCESS_KEY }}
  BRANCH: ${{ github.ref }}
  BUILD_SUFFIX: 'desktop-pr'
  JIRA_PROJECT_KEY: 'MM'
  MM_TEST_SERVER_URL: "https://localhost:8065"
  PULL_REQUEST_BASE_URL: "https://github.com/mattermost/desktop/pull/"
  TEST_CYCLE_LINK_PREFIX: ${{ secrets.MM_DESKTOP_E2E_TEST_CYCLE_LINK_PREFIX }}
  TYPE: ${{ github.event_name == 'pull_request' && 'PR' || '' }}
  ZEPHYR_API_KEY: ${{ secrets.MM_DESKTOP_E2E_ZEPHYR_API_KEY }}
  ZEPHYR_ENABLE: 'true'
  ZEPHYR_ENVIRONMENT_NAME: 'Desktop app'
  ZEPHYR_FOLDER_ID: "3256491"

jobs:
  e2e-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:

      - name: Check out code
        uses: actions/checkout@v3.5.3

      - name: Set up Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set Environment Variables
        run: |
          echo "BUILD_ID=${{ github.run_id }}-${{ env.BUILD_SUFFIX}}-${{ runner.os }}" >> $GITHUB_ENV
          echo "BUILD_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "PULL_REQUEST=${PULL_REQUEST_BASE_URL}${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Print Environment Variables
        run: |
          echo "PULL_REQUEST: ${{ env.PULL_REQUEST }}"
          echo "BUILD_ID: ${{ env.BUILD_ID }}"
          echo "BRANCH: ${{ env.BRANCH }}"
          echo "MM_TEST_SERVER_URL: ${{ env.MM_TEST_SERVER_URL }}"
          echo "ZEPHYR_ENABLE: ${{ env.ZEPHYR_ENABLE }}"
          echo "ZEPHYR_ENVIRONMENT_NAME: ${{ env.ZEPHYR_ENVIRONMENT_NAME }}"
          echo "ZEPHYR_FOLDER_ID: ${{ env.ZEPHYR_FOLDER_ID }}"
          echo "BUILD_TAG: ${{ env.BUILD_TAG }}"
          echo "PULL_REQUEST: ${{ env.PULL_REQUEST }}"
          echo "BUILD_SUFFIX: ${{ env.BUILD_SUFFIX }}"
          echo "TYPE: ${{ env.TYPE }}"
          echo "JIRA_PROJECT_KEY: ${{ env.JIRA_PROJECT_KEY }}"

      - name: Desktop Install nodejs dependencies
        run: npm ci

#   Linux

      - name: Install packages (Ubuntu OS)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libxtst-dev libpng++-dev
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Checkout mattermost
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          repository: mattermost/mattermost
          path: mattermost

      - name: Run mattermsot server
        run: |
          cd mattermost/e2e-tests
          echo "SERVER_IMAGE=mattermost/mattermost-enterprise-edition:release-8.0" >.ci/env
          make start-server && make prepare-server

      - name: Run Playwright tests (Ubuntu OS)
        if: matrix.os == 'ubuntu-latest'
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm run test:e2e || true # making job pass even if the tests fail due to flakyness
          npm run test:e2e:send-report
